[package]
name = "IonSolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
image = "0.24.7"
ocl = "0.19.4"
rayon = "1.8.0"

[features]
headless = []