[package]
name = "sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
micro_ndarray = "0.2"
multicall = "0.1.3"
readformat = "0.1.2"
image = "0.24"
egui = "0.21.0"
eframe = "0.21.3"
